### ISSUE TITLE
not Web server, but a WebSocket Endpoint

### ISSUE THREAD

**Issue by HiZhaoxiaoyang** [Igoorx/PyRoyale#14]
i deploy this project as follow to a remote centos, but receive message as below:

> http://zhaoxy.top:9000/royale/index.html
AutobahnPython 19.7.1
I am not Web server, but a WebSocket Endpoint.
You can talk to me using the WebSocket protocol.
For more information, please see:
Autobahn

how to fix it ,thanx.

**Comment by Igoorx** [comment]
This repository is just the we game server, please follow the instructions in the TUTORIAL.md file
