### ISSUE TITLE
invite expired

### ISSUE THREAD

**Issue by Nikolay0054** [Igoorx/PyRoyale#3]
discord invitation is expired

**Comment by Igoorx** [comment]
New invite added in https://github.com/Igoorx/PyRoyale/commit/099059a6a35b69a347113c44e1b1c3d7b425cac7

**Comment by Igoorx** [comment]
New invite added in https://github.com/Igoorx/PyRoyale/commit/099059a6a35b69a347113c44e1b1c3d7b425cac7
