### ISSUE TITLE
How to play

### ISSUE THREAD

**Issue by weidongq** [Igoorx/PyRoyale#4]
Thanks for sharing!

After I opened the server.exe, how can I play? 
When I open ip:9000 in chrome or firefox, it tell me " am not Web server, but a WebSocket Endpoint."
So do I need a client?
Thanks!

**Comment by Igoorx** [comment]
I've just created the tutorial page, take a look: https://github.com/Igoorx/PyRoyale/blob/master/TUTORIAL.md
