### ISSUE TITLE
Server stops responding

### ISSUE THREAD

**Issue by Igoorx** [Igoorx/PyRoyale#7]
From nowhere the server stops responding even to SIGNALs, like its got deadlocked... But that's weird, we don't use threads, and I couldn't find any potential infinite loop...
![ScreenShot](https://i.imgur.com/fV4MQpy.png)

**Comment by gyorokpeter** [comment]
Can you even not attach gdb? or strace?

**Comment by Igoorx** [comment]
> Can you even not attach gdb? or strace?

I tried strace to see the output, but it didn't show any output, maybe the reactor was stopped.

**Comment by Igoorx** [comment]
This seems to be fixed
